import streamlit as st

def explain(case):
  if case == 'Glioma':
    st.markdown('A glioma is a type of primary tumor that starts in the glial cells of the brain or spinal cord. They are malignant but some are extremely slow to develop. Gliomas comprise about 30% of all brain and central nervous system tumors and 80% of all malignant brain tumors. There are a few common types that include astrocytoma (cancer of astrocytes), glioblastoma (an aggressive form of astrocytoma), oligodendroglioma (cancer of oligodendrocytes), and ependymoma (cancer of ependymal cells).') 
  elif case == 'Meningioma':
    st.markdown('Meningioma, also known as meningeal tumor, is typically a slow-growing tumor that forms from the meninges, the membranous layers surrounding the brain and spinal cord. Symptoms depend on the location and occur as a result of the tumor pressing on nearby tissue. Many cases never produce symptoms. Occasionally seizures, dementia, trouble talking, vision problems, one sided weakness, or loss of bladder control may occur. Risk factors include exposure to ionizing radiation such as during radiation therapy, a family history of the condition, and neurofibromatosis type 2. They appear to be able to form from a number of different types of cells including arachnoid cells. Diagnosis is typically by medical imaging. If there are no symptoms, periodic observation may be all that is required. Most cases that result in symptoms can be cured by surgery. Following complete removal fewer than 20% recur. If surgery is not possible or all the tumor cannot be removed, radiosurgery may be helpful. Chemotherapy has not been found to be useful. A small percentage grow rapidly and are associated with worse outcomes. About one per thousand people in the United States are currently affected. Onset is usually in adults. In this group they represent about 30% of brain tumors. Women are affected about twice as often as men. Meningiomas were reported as early as 1614 by Felix Plater.')
  elif case == 'No tumor':
    st.markdown('Your brain is healthy and does not contain any tumors')
  else:
    st.markdown('Pituitary tumors are unusual growths that develop in the pituitary gland. This gland is an organ about the size of a pea. It is located behind the nose at the base of the brain. Some of these tumors cause the pituitary gland to make too much of certain hormones that control important body functions. Others can cause the pituitary gland to make too little of those hormones. Most pituitary tumors are benign. That means they are not cancerous. Another name for these noncancerous tumors is pituitary adenomas. Most adenomas stay in the pituitary gland or in the tissue around it, and they grow slowly. They typically don't spread to other parts of the body. Pituitary tumors can be treated in several ways. The tumor may be removed with surgery. Or its growth may be controlled with medications or radiation therapy. Sometimes, hormone levels are managed with medicine. Your health care provider may suggest a combination of these treatments. In some cases, observation, also called a ''wait-and-see'' approach, may be the right choice. Pituitary tumors are unusual growths that develop in the pituitary gland. This gland is an organ about the size of a pea. It's located behind the nose at the base of the brain. Some of these tumors cause the pituitary gland to make too much of certain hormones that control important body functions. Others can cause the pituitary gland to make too little of those hormones. Most pituitary tumors are benign. That means they are not cancerous. Another name for these noncancerous tumors is pituitary adenomas. Most adenomas stay in the pituitary gland or in the tissue around it, and they grow slowly. They typically don't spread to other parts of the body. Pituitary tumors can be treated in several ways. The tumor may be removed with surgery. Or its growth may be controlled with medications or radiation therapy. Sometimes, hormone levels are managed with medicine. Your health care provider may suggest a combination of these treatments. In some cases, observation, also called a ''wait-and-see'' approach, may be the right choice.')
  return
